version: 0.2
phases:
  pre_build:
    commands:
      - echo "entered the pre-build phase"
  build:
    commands:
      - echo "entered the build phase"
      - maven clean prepare-package war:explode
  post_build:
    commands:
      - echo "entered the post build phase"
      - mv target/deploy ./
  artifacts:
    files:
      - deploy/**/*

